/** Statische DE-Parlamentliste (UI-Fallback ohne API-Cold-Start). */
import type { Parliament } from "@/lib/api";

export const DE_PARLIAMENTS: Parliament[] = [
  {
    id: "de_bundestag",
    name: "Deutscher Bundestag",
    country: "DE",
    level_kind: "national",
    state_code: null,
    seats_total: 630,
    election_system_key: "de_bundestag_2023",
    shortcut: "Bundestag",
    next_election_date: null,
    next_election_note:
      "voraussichtlich Frühjahr 2029 (regulärer Turnus 4 Jahre nach BTW 2025; Termin noch nicht festgesetzt)",
  },
  {
    id: "de_bw_landtag",
    name: "Landtag von Baden-Württemberg",
    country: "DE",
    level_kind: "state",
    state_code: "DE-BW",
    seats_total: 120,
    election_system_key: "de_bw_lt",
    shortcut: "BW",
    next_election_date: null,
    next_election_note:
      "voraussichtlich Frühjahr 2031 (nach Landtagswahl 8. März 2026; Termin noch nicht festgesetzt)",
  },
  {
    id: "de_by_landtag",
    name: "Bayerischer Landtag",
    country: "DE",
    level_kind: "state",
    state_code: "DE-BY",
    seats_total: 180,
    election_system_key: "de_by_lt",
    shortcut: "BY",
    next_election_date: null,
    next_election_note:
      "voraussichtlich Herbst 2028 (Termin noch nicht offiziell festgesetzt)",
  },
  {
    id: "de_be_abgeordnetenhaus",
    name: "Abgeordnetenhaus von Berlin",
    country: "DE",
    level_kind: "state",
    state_code: "DE-BE",
    seats_total: 130,
    election_system_key: "de_be_agH",
    shortcut: "BE",
    next_election_date: "2026-09-20",
    next_election_note: null,
  },
  {
    id: "de_bb_landtag",
    name: "Landtag Brandenburg",
    country: "DE",
    level_kind: "state",
    state_code: "DE-BB",
    seats_total: 88,
    election_system_key: "de_bb_lt",
    shortcut: "BB",
    next_election_date: null,
    next_election_note:
      "voraussichtlich Herbst 2029 (Termin noch nicht offiziell festgesetzt)",
  },
  {
    id: "de_hb_buergerschaft",
    name: "Bremische Bürgerschaft",
    country: "DE",
    level_kind: "state",
    state_code: "DE-HB",
    seats_total: 87,
    election_system_key: "de_hb_bs",
    shortcut: "HB",
    next_election_date: "2027-05-30",
    next_election_note: null,
  },
  {
    id: "de_hh_buergerschaft",
    name: "Hamburgische Bürgerschaft",
    country: "DE",
    level_kind: "state",
    state_code: "DE-HH",
    seats_total: 121,
    election_system_key: "de_hh_bs",
    shortcut: "HH",
    next_election_date: null,
    next_election_note:
      "voraussichtlich Frühjahr/Winter 2030 (Termin noch nicht offiziell festgesetzt)",
  },
  {
    id: "de_he_landtag",
    name: "Hessischer Landtag",
    country: "DE",
    level_kind: "state",
    state_code: "DE-HE",
    seats_total: 110,
    election_system_key: "de_he_lt",
    shortcut: "HE",
    next_election_date: null,
    next_election_note:
      "voraussichtlich Herbst 2028 (Termin noch nicht offiziell festgesetzt)",
  },
  {
    id: "de_mv_landtag",
    name: "Landtag Mecklenburg-Vorpommern",
    country: "DE",
    level_kind: "state",
    state_code: "DE-MV",
    seats_total: 71,
    election_system_key: "de_mv_lt",
    shortcut: "MV",
    next_election_date: "2026-09-20",
    next_election_note: null,
  },
  {
    id: "de_ni_landtag",
    name: "Niedersächsischer Landtag",
    country: "DE",
    level_kind: "state",
    state_code: "DE-NI",
    seats_total: 135,
    election_system_key: "de_ni_lt",
    shortcut: "NI",
    next_election_date: "2027-09-26",
    next_election_note: null,
  },
  {
    id: "de_nw_landtag",
    name: "Landtag Nordrhein-Westfalen",
    country: "DE",
    level_kind: "state",
    state_code: "DE-NW",
    seats_total: 181,
    election_system_key: "de_nw_lt",
    shortcut: "NW",
    next_election_date: "2027-04-25",
    next_election_note: null,
  },
  {
    id: "de_rp_landtag",
    name: "Landtag Rheinland-Pfalz",
    country: "DE",
    level_kind: "state",
    state_code: "DE-RP",
    seats_total: 101,
    election_system_key: "de_rp_lt",
    shortcut: "RP",
    next_election_date: null,
    next_election_note:
      "voraussichtlich Frühjahr 2031 (nach Landtagswahl 22. März 2026; Termin noch nicht festgesetzt)",
  },
  {
    id: "de_sl_landtag",
    name: "Landtag des Saarlandes",
    country: "DE",
    level_kind: "state",
    state_code: "DE-SL",
    seats_total: 51,
    election_system_key: "de_sl_lt",
    shortcut: "SL",
    next_election_date: "2027-04-18",
    next_election_note: null,
  },
  {
    id: "de_sn_landtag",
    name: "Sächsischer Landtag",
    country: "DE",
    level_kind: "state",
    state_code: "DE-SN",
    seats_total: 120,
    election_system_key: "de_sn_lt",
    shortcut: "SN",
    next_election_date: null,
    next_election_note:
      "voraussichtlich Herbst 2029 (Termin noch nicht offiziell festgesetzt)",
  },
  {
    id: "de_st_landtag",
    name: "Landtag von Sachsen-Anhalt",
    country: "DE",
    level_kind: "state",
    state_code: "DE-ST",
    seats_total: 83,
    election_system_key: "de_st_lt",
    shortcut: "ST",
    next_election_date: "2026-09-06",
    next_election_note: null,
  },
  {
    id: "de_sh_landtag",
    name: "Schleswig-Holsteinischer Landtag",
    country: "DE",
    level_kind: "state",
    state_code: "DE-SH",
    seats_total: 69,
    election_system_key: "de_sh_lt",
    shortcut: "SH",
    next_election_date: "2027-04-18",
    next_election_note: null,
  },
  {
    id: "de_th_landtag",
    name: "Thüringer Landtag",
    country: "DE",
    level_kind: "state",
    state_code: "DE-TH",
    seats_total: 88,
    election_system_key: "de_th_lt",
    shortcut: "TH",
    next_election_date: null,
    next_election_note:
      "voraussichtlich Herbst 2029 (Termin noch nicht offiziell festgesetzt)",
  },
];

export function parliamentIdFromPath(pathname: string): string | null {
  const m = pathname.match(/^\/parlament\/([^/]+)/);
  return m?.[1] ?? null;
}

export function displayNameForParliament(
  id: string,
  list: Parliament[] = DE_PARLIAMENTS,
): string {
  return list.find((p) => p.id === id)?.name ?? id;
}
